apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-cfl-deployment
  labels:
    app: nginx-cfl
spec:
  replicas: 4  # Deux répliques de l'application pour la haute disponibilité
  selector:
    matchLabels:
      app: nginx-cfl
  template:
    metadata:
      labels:
        app: nginx-cfl
    spec:
      containers:
      - name: nginx
        image: nginx:1.27.1-alpine-perl
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-cfl-service
spec:
  type: NodePort
  selector:
    app: nginx-cfl
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005  # Exposer le service sur le port 30008
